"""google staf

Revision ID: 242d63a77966
Revises: 165a332857f0
Create Date: 2026-06-01 18:40:04.088393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d63a77966'
down_revision: Union[str, Sequence[str], None] = '165a332857f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_drive_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_drive_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_name')
    op.drop_column('users', 'google_email')
    op.drop_column('users', 'google_drive_refresh_token')
    op.drop_column('users', 'google_drive_access_token')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ###
