"""init

Revision ID: 70f6c64055b2
Revises: 
Create Date: 2026-06-09 06:50:44.527673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f6c64055b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'google_email')
    op.drop_column('users', 'google_name')
    op.drop_column('users', 'google_drive_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_drive_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
