"""Add missing User columns

Revision ID: 8519d2092424
Revises: 35f2171abb19
Create Date: 2026-06-15 07:08:19.894697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8519d2092424'
down_revision: Union[str, Sequence[str], None] = '35f2171abb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('compression_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('size_before', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'size_before')
    op.drop_column('users', 'compression_count')
    # ### end Alembic commands ###
