"""update Users model

Revision ID: b36f3f15c33b
Revises: 5e3035174819
Create Date: 2026-05-30 13:19:52.421596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36f3f15c33b'
down_revision: Union[str, Sequence[str], None] = '5e3035174819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ips', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('blocked_ips', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'blocked_ips')
    op.drop_column('users', 'ips')
    # ### end Alembic commands ###
